# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]
env:
  # Use alternative image when running on GitHub workflows CI to avoid potential
  # rate limiting when executing jobs in parallel: they can't cache docker images
  # and always pull.
  #
  # To update this image, generate a personal token with write:packages scope
  # on https://github.com/settings/tokens and authenticate yourself locally with
  # "docker login https://docker.pkg.github.com -u <github-username>" using the
  # newly generated token as password.
  # Once logged in, tag an new image:
  #   docker tag shiftcrypto/bitbox-wallet-app:VERSION \
  #   docker.pkg.github.com/digitalbitbox/bitbox-wallet-app/ci-builder:VERSION
  # and push as usual:
  #   docker push docker.pkg.github.com/digitalbitbox/bitbox-wallet-app/ci-builder:VERSION
  # Lastly, update the next line to use the newly pushed image version.
  # See docs for more details:
  # https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages
  #
  # Keep this in sync with default in scripts/travis-ci.sh.
  CI_IMAGE: docker.pkg.github.com/digitalbitbox/bitbox-wallet-app/ci-builder:6
  TRAVIS_BUILD_DIR: ${{github.workspace}}

jobs:
  #golangci:
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - name: Clone the repo
  #      uses: actions/checkout@v2
  #    - name: Run golangci-lint
  #      uses: golangci/golangci-lint-action@v1
  #      with:
  #        # Keep this in sync with the version in envinit make target.
  #        version: v1.27
  #test-lint:
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - name: Clone the repo
  #      uses: actions/checkout@v2
  #    - name: Docker login
  #      run: docker login -u ${{github.actor}} -p ${{github.token}} https://docker.pkg.github.com
  #    - name: Run CI script
  #      # The script also runs golang-ci but it's ok: doesn't take too long and may be useful
  #      # to keep its linter errors in this log, too.
  #      run: ./scripts/travis-ci.sh ci
  #      env:
  #        TRAVIS_OS_NAME: linux
  #android:
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - name: Clone the repo
  #      uses: actions/checkout@v2
  #    - name: Docker login
  #      run: docker login -u ${{github.actor}} -p ${{github.token}} https://docker.pkg.github.com
  #    - name: Build Android
  #      run: ./scripts/travis-ci.sh android
  #      env:
  #        TRAVIS_OS_NAME: linux
  #    - name: Upload APK
  #      uses: actions/upload-artifact@v2
  #      with:
  #        path: frontends/android/BitBoxApp/app/build/outputs/apk/debug/app-debug.apk
  #        name: BitBoxApp-android-${{github.sha}}.apk
  #qt-linux:
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - name: Clone the repo
  #      uses: actions/checkout@v2
  #    - name: Docker login
  #      run: docker login -u ${{github.actor}} -p ${{github.token}} https://docker.pkg.github.com
  #    - name: Build Qt-Linux
  #      run: ./scripts/travis-ci.sh qt-linux
  #      env:
  #        TRAVIS_OS_NAME: linux
  #    - name: Upload AppImage
  #      uses: actions/upload-artifact@v2
  #      with:
  #        path: frontends/qt/build/linux/BitBoxApp-*.AppImage
  #        name: BitBoxApp-linux-${{github.sha}}.AppImage
  #    - name: Upload deb
  #      uses: actions/upload-artifact@v2
  #      with:
  #        path: frontends/qt/build/linux/bitbox_*.deb
  #        name: BitBoxApp-linux-${{github.sha}}.deb
  #    - name: Upload rpm
  #      uses: actions/upload-artifact@v2
  #      with:
  #        path: frontends/qt/build/linux/bitbox-*.rpm
  #        name: BitBoxApp-linux-${{github.sha}}.rpm
  macos:
    runs-on: macos-10.15
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Build macOS app
        run: ./scripts/travis-ci.sh qt-osx
        env:
          TRAVIS_OS_NAME: osx
      - name: Archive app
        run: >
          pushd ~/go/src/github.com/digitalbitbox/bitbox-wallet-app/frontends/qt/build/osx;
          ditto -c -k --keepParent BitBox.app ${{github.workspace}}/BitBoxApp-macos.zip;
          popd;
      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          path: BitBoxApp-macos.zip
          name: BitBoxApp-macos-${{github.sha}}.zip
